Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      ArtifactRelation:
        centos_7:
          ArtifactId: ${Artifact.Artifact.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact.ArtifactVersion}
      SupplierTemplateConfigs:
        - Name: 单机版
          Url: 
            https://service-info-private.oss-cn-hangzhou.aliyuncs.com/1853370294850618/template/17921e3e-90c5-4282-82aa-1cc2e3250864.json?Expires=1744874915&OSSAccessKeyId=LTAI5tCYphFhocJemeMWmXst&Signature=JmZB66mCA3CXB%2B7UXH7Uo9xIoz4%3D
          PredefinedParameters:
            - Name: 热卖套餐，特价99元/年（限购1台）
              Parameters:
                EcsInstanceType:
                  - ecs.e-c1m1.large
                SystemDiskCategory: cloud_essd_entry
                SystemDiskSize: 40
                InternetChargeType: PayByBandwidth
                InternetMaxBandwidthOut: 3
                PayPeriodUnit: Month
                PayPeriod: 12
                PayType: PrePaid
              OrderList:
                - EcsInstanceType
                - SystemDiskCategory
                - SystemDiskSize
                - InternetChargeType
                - InternetMaxBandwidthOut
                - PayPeriodUnit
                - PayPeriod
                - PayType
              Type: Normal
              Description: 固定带宽不限流量，新老同享，上云首选！
            - Name: 尝鲜套餐，只需0.3元/小时
              Parameters:
                EcsInstanceType:
                  - ecs.e-c1m1.large
                SystemDiskCategory: cloud_essd_entry
                SystemDiskSize: 40
                InternetChargeType: PayByBandwidth
                InternetMaxBandwidthOut: 3
                PayType: PostPaid
              OrderList:
                - EcsInstanceType
                - SystemDiskCategory
                - SystemDiskSize
                - InternetChargeType
                - InternetMaxBandwidthOut
                - PayPeriodUnit
                - PayPeriod
                - PayType
              Type: Normal
              Description: 可用300元学生专属代金券抵扣！
            - Name: 自定义套餐
              Parameters: {}
              OrderList:
                - EcsInstanceType
                - SystemDiskCategory
                - SystemDiskSize
                - InternetChargeType
                - InternetMaxBandwidthOut
                - PayPeriodUnit
                - PayPeriod
                - PayType
              Type: Custom
          AllowedRegions:
            - cn-beijing
            - cn-hangzhou
            - cn-heyuan
    TemplateConfigs:
      - Name: 单机版
        Url: ros_templates/template1.yaml
        AllowedRegions:
          - cn-beijing
          - cn-hangzhou
          - cn-heyuan
        PredefinedParameters:
          - Name: 热卖套餐，特价99元/年（限购1台）
            Parameters:
              EcsInstanceType:
                - ecs.e-c1m1.large
              SystemDiskCategory: cloud_essd_entry
              SystemDiskSize: 40
              InternetChargeType: PayByBandwidth
              InternetMaxBandwidthOut: 3
              PayPeriodUnit: Month
              PayPeriod: 12
              PayType: PrePaid
            OrderList:
              - EcsInstanceType
              - SystemDiskCategory
              - SystemDiskSize
              - InternetChargeType
              - InternetMaxBandwidthOut
              - PayPeriodUnit
              - PayPeriod
              - PayType
            Type: Normal
            Description: 固定带宽不限流量，新老同享，上云首选！
          - Name: 尝鲜套餐，只需0.3元/小时
            Parameters:
              EcsInstanceType:
                - ecs.e-c1m1.large
              SystemDiskCategory: cloud_essd_entry
              SystemDiskSize: 40
              InternetChargeType: PayByBandwidth
              InternetMaxBandwidthOut: 3
              PayType: PostPaid
            OrderList:
              - EcsInstanceType
              - SystemDiskCategory
              - SystemDiskSize
              - InternetChargeType
              - InternetMaxBandwidthOut
              - PayPeriodUnit
              - PayPeriod
              - PayType
            Type: Normal
            Description: 可用300元学生专属代金券抵扣！
          - Name: 自定义套餐
            Parameters: {}
            OrderList:
              - EcsInstanceType
              - SystemDiskCategory
              - SystemDiskSize
              - InternetChargeType
              - InternetMaxBandwidthOut
              - PayPeriodUnit
              - PayPeriod
              - PayType
            Type: Custom
        ArchitectureDiagramUrl: 
          https://service-info-private.oss-cn-hangzhou.aliyuncs.com/1853370294850618/architecture/架构图.jpg?Expires=1744874915&OSSAccessKeyId=LTAI5tCYphFhocJemeMWmXst&Signature=m9RTtzHqf%2F4VljOu%2BJgixENOJCQ%3D
        DeployScene: ECS
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      Prefix: amap-
      UseDefaultValue: false
  OperationMetadata:
    SupportBackup: false
    PrometheusConfigMap:
      单机版:
        EnablePrometheus: false
  ServiceType: private
  ServiceInfo:
    - Agreements: []
      Image: resources/icons/service_logo_zh-CN.png
      Locale: zh-CN
      Name: Open WebUI高德MCP
      ShortDescription: 使用AI模型，引入高德地图MCP服务，制作AI Agent，可以理解用户意图，同时使用高德地图精确的地理位置信息、天气查询能力、骑行/步行/驾车路径规划能力、周边搜索等能力，为用户提供精确、真实的出行、游玩建议。
      Softwares: []
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact:
    ArtifactType: EcsImage
    ArtifactName: amap
    Description: amap
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    SourceImageId: aliyun_3_x64_20G_alibase_20240819.vhd
    SystemDiskSize: 40
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 10
    CommandType: RunShellScript
    Timeout: 10800
    Tags: [ ]
    CommandContent: |-
        # 安装docker-ce
        yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        yum makecache
        yum install -y wget curl unzip git jq
        yum install -y docker-ce
        sudo systemctl enable --now docker.service

        # 创建mcp目录，用于存放mcp配置文件
        mkdir -p /root/mcp && cd mcp
        # 安装OpenWebUI
        cat > /root/mcp/docker-compose.yaml << "EOF"
        services:
          open-webui:
            image: ghcr.io/open-webui/open-webui:latest
            container_name: open-webui
            volumes:
              - open-webui:/app/backend/data
            ports:
              - 8080:8080
            extra_hosts:
              - host.docker.internal:host-gateway
            restart: unless-stopped
            environment:
              - 'ENABLE_OPENAI_API=True'
              - 'ENABLE_OLLAMA_API=False'
              - 'OPENAI_API_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1'
              - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
        volumes:
          ollama: {}
          open-webui: {}
        EOF

        docker compose up -d

        # 安装python
        yum install python3.11 -y
        # 创建python虚拟环境
        python3.11 -m venv venv
        # 启动虚拟环境
        source venv/bin/activate
        # 安装mcpo
        pip install mcpo
        # 下载nvm
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
        # 配置nvm
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        # 安装node，以node版本22为例
        nvm install 22
        # 安装高德MCP server
        npm install @amap/amap-maps-mcp-server
        cat > /root/mcp/config.json << EOF
        {
          "mcpServers": {
            "amap-maps": {
              "command": "npx",
              "args": ["-y", "@amap/amap-maps-mcp-server"],
              "env": {
                "AMAP_MAPS_API_KEY": ""
              }
            }
          }
        }
        EOF
